### ISSUE TITLE
'Clean' base implementation?

### ISSUE THREAD

**Issue by hanno-becker** [Emill/X25519-AArch64#2]
Thank you @Emill for this interesting work! Could you make available a 'clean' baseline assembly implementation which demonstrates the algorithms as well as SIMD vs. scalar splitting, but does not do any pipeline-specific interleaving? I am interested in trying to automate the interleaving via https://github.com/slothy-optimizer/slothy.

**Comment by hanno-becker** [comment]
@Emill FYI your work was an inspiration for https://eprint.iacr.org/2022/1303 -- thank you.

**Comment by Emill** [comment]
Nice! I hope this could make it's way into OpenSSL etc., since the speed there is not the best for in-order ARM processors. Maybe with your tool it's possible to get more high quality implementations for various algorithms that could be adopted.

**Comment by hanno-becker** [comment]
@Emill Yes that would be very nice indeed. Note that even for OOO processors, speedups can be unlocked, as the Cortex-A72 example shows. Unfortunately, I don't have bandwidth to drive such integration at the moment, but could only advise / explain the code / provide the occasional bugfix.
